defaults:
  - reducer@visualizations.reducer: pca_tsne

visualizations:
  _target_: pretraining.evaluation.visualizations.VisualizationEvaluator

  eval_name: space_visualizer
  eval_freq: 5
  reducer_name: pca and tsne
  sample_pixels: 10000
  all: true
  one_view: true
  one_image: true
  mean: ${data.eval.augmentation.normalize.mean}
  std: ${data.eval.augmentation.normalize.std}
  cf_suffixes: ['sc', 'pe', 'sc_pe']