_target_: pretraining.losses.supervised_loss_coord.SupervisedCoordContrastiveLoss

temperature: 0.7
bg_anchors: false
use_labels: false
chunk_divs: 2

matching_rule:
  inter_view_same_pixel: 1
  inter_view_same_class: 1
  inter_view_different_class: 0
  inter_image_same_class: 1
  inter_image_different_class: 0